### ISSUE TITLE
Incompatible ROM

### ISSUE THREAD

**Issue by PenGuy96** [marcrobledo/super-game-boy-border-injector#10]
Mega Man Xtreme (USA, Europe); El nuevo borde funciona bien, pero la paleta por defecto del juego sigue predominando.

Money Idol Exchanger (Japan) y Pocket Puyo Puyo Sun (Japan): Los bordes nuevos sólo aparecen antes de que el juego arranque, luego son reemplazados por los originales. En el caso del juego de Puyo Puyo se puede ver la paleta nueva, en Money Idol es posible que no funcione por tener múltiples paletas y más de alguna compartiendo pantalla.

**Comment by marcrobledo** [comment]
Las paletas de SGB (al igual que los bordes) están dentro del código del juego original y no existe un método universal para evitar que predominen. Habría que trabajar individualmente cada juego y eso es una tarea casi infinita 😅

El tema de los bordes es factible arreglar en algunos juegos, las paletas es más complicado.

- Mega Man Xtreme es un juego de GBC. Si no me equivoco, no tenía paletas ni borde de SGB. Lo que seguramente esté ocurriendo es que estás jugando en un emulador que muestra el borde de SGB pero el juego lo ejecuta en modo GBC, por eso ves color. Si quieres ver tu paleta de SGB, tendrás que poner el emulador en modo SGB (no GBC).
- He logrado solucionar el Money Idol Exchanger, ya soporta borde inyectado, aunque ahora la paleta original ha dejado de funcionar. Este tipo de problemas es habitual en juegos que ya soportaban SGB.
- El Pocket Puyo Puyo Tsuu desgraciadamente le he dedicado demasiado tiempo sin éxito, lo siento :-(

**Comment by PenGuy96** [comment]
> Las paletas de SGB (al igual que los bordes) están dentro del código del juego original y no existe un método universal para evitar que predominen. Habría que trabajar individualmente cada juego y eso es una tarea casi infinita 😅
> 
> El tema de los bordes es factible arreglar en algunos juegos, las paletas es más complicado.
> 
> * Mega Man Xtreme es un juego de GBC. Si no me equivoco, no tenía paletas ni borde de SGB. Lo que seguramente esté ocurriendo es que estás jugando en un emulador que muestra el borde de SGB pero el juego lo ejecuta en modo GBC, por eso ves color. Si quieres ver tu paleta de SGB, tendrás que poner el emulador en modo SGB (no GBC).
> * He logrado solucionar el Money Idol Exchanger, ya soporta borde inyectado, aunque ahora la paleta original ha dejado de funcionar. Este tipo de problemas es habitual en juegos que ya soportaban SGB.
> * El Pocket Puyo Puyo Tsuu desgraciadamente le he dedicado demasiado tiempo sin éxito, lo siento :-(



> Las paletas de SGB (al igual que los bordes) están dentro del código del juego original y no existe un método universal para evitar que predominen. Habría que trabajar individualmente cada juego y eso es una tarea casi infinita 😅
> 
> El tema de los bordes es factible arreglar en algunos juegos, las paletas es más complicado.
> 
> * Mega Man Xtreme es un juego de GBC. Si no me equivoco, no tenía paletas ni borde de SGB. Lo que seguramente esté ocurriendo es que estás jugando en un emulador que muestra el borde de SGB pero el juego lo ejecuta en modo GBC, por eso ves color. Si quieres ver tu paleta de SGB, tendrás que poner el emulador en modo SGB (no GBC).
> * He logrado solucionar el Money Idol Exchanger, ya soporta borde inyectado, aunque ahora la paleta original ha dejado de funcionar. Este tipo de problemas es habitual en juegos que ya soportaban SGB.
> * El Pocket Puyo Puyo Tsuu desgraciadamente le he dedicado demasiado tiempo sin éxito, lo siento :-(

Creo que hubo una confusión y me disculpo por no haberlo dejado claro: 
>* En el caso de Megaman Xtreme, este ya contaba con una paleta oculta para el Super Game Boy (consultar en su página de The Cutting Rom Floor [),](https://tcrf.net/Mega_Man_Xtreme#Unused_SGB_Palettes) el problema es que en su momento no la pude reemplazar, pero sí pude aplicarle un borde como tal.
>*El Puyo Puyo que quería cambiarle el borde era al Sun (el tercer juego) no al Tsuu (el segundo)

Aún así, agradezco que hayas hecho completamente compatible el Money Puzzle Exchanger para el inyector 👋

**Comment by marcrobledo** [comment]
Oh, perdón, me confundí.

Le he dado una oportunidad al Sun ahora mismo y tengo el mismo problema que con el Tsuu, parece que usan el mismo motor. Lo siento :-(
