### ISSUE TITLE
Broken ROM: Wave Race

### ISSUE THREAD

**Issue by Mime64** [marcrobledo/super-game-boy-border-injector#11]
Generated a border to inject into Wave Race, but the game just hangs on load.
Injected the same border into Super Mario Land with no issues.

![waverace](https://github.com/marcrobledo/super-game-boy-border-injector/assets/20603668/f8b43969-15c6-4260-a29b-c13b107013f5)

**Comment by marcrobledo** [comment]
I see. Looks like the game is using a MBC2, which requires a small change in code for bank switching.
It's easily fixable, but give me a couple of days, please!

**Comment by marcrobledo** [comment]
SGB Border Injector version bumped to 1.3!

This should work with Wave Race and other MBC2 games as well.

Thank you for reporting, we've increased compatibility once again, yay!
